### ISSUE TITLE
Chokes on spaces in password...

### ISSUE THREAD

**Issue by JaredVAvalara** [jazzdev/node-netrc#1]
quick alternative (no testing)

```
    // var tokens = data.split(/[ \t\n\r]+/);
    var tokens = [];
    var re = /^\s*(\w+)\s+(.+)$/gm;
    while (_ = re.exec(data)) {
      tokens.push(_[1])
      tokens.push(_[2])
    };
```

**Comment by jazzdev** [comment]
machines can have an account also

  machine foo user chris password secret account uw

So just accepting spaces doesn't work. I added support for
hex escapes instead, so you can do

  machine foo user chris password really\x20secret

(hex 20 is space)
